### ISSUE TITLE
Only for specific groups

### ISSUE THREAD

**Issue by extreme-sysadminning** [jancborchardt/lsd#7] opened 2018-04-04 17:41 UTC
Activating this only for my parents, who are in their own group, would be nice.

**Comment by jancborchardt** [comment] 2018-04-05 09:16
> Activating this only for my parents

:D 

@extreme-sysadminning this is a duplicate of https://github.com/jancborchardt/lsd/issues/5 though, so let’s continue there. :)

**Closed by jancborchardt** 2018-04-05 09:16 UTC
